apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
type: Opaque
data:
  RAZORPAY_KEY_ID: "rzp_test_ai3pssiWfZuKDy"
  RAZORPAY_KEY_SECRET: "0yUzxRxHS140W6S3UOYrmlko"
  GOOGLE_CLIENT_SECRET: "YOUR_BASE64_ENCODED_GOOGLE_SECRET"